audeering/sphinx-audeering-theme

docs/conf.py
Disable the links in the footer section that point to our internal documentation.
=> DOC: disable footer links to internal docs

.github/workflows/test.yml
The tests were working before, even I removed or forgot the doc requirements to install. This is fixed by this pull request.
=> TST: add installation of doc requirements

README.rst
The link was pointing to the license file of `audiofile` before.
=> DOC: fix license link

.github/workflows/publish.yml
This creates an release on Github now from every tag automatically.
It also reads the last changes to `CHANGELOG.rst` automatically and adds it as release message.
=> Automatic release

.github/workflows/publish.yml
Automatic extraction of the CHANGELOG is working, but only a single line was added to https://github.com/audeering/sphinx-audeering-theme/releases/tag/v1.0.3
This applies the fix described at https://github.com/actions/create-release/pull/11#issuecomment-640071918 to support multiline entries.
=> Support multiline changelog in automatic release

.github/workflows/publish.yml
This wil insert only the bullet points from the CHANGELOG to the Github release entry.
=> Remove header from automatic changelog extraction

CONTRIBUTING.rst
Update making a release instructions in CONTRIBUTING, it's much easier now.
=> DOC: update release instructions to Github

sphinx_audeering_theme/layout.html
Closes #23 
It seems to be that they introduced a new `scripts` block in the RTD theme. This is [referenced in search.html](https://github.com/readthedocs/sphinx_rtd_theme/blob/e2b60d7e7b2b6feb8a45b224950608ad11668a7e/sphinx_rtd_theme/search.html#L13) in order to add the JS file. As we hadn't the block defined in our `layout.html` file it was not inserting it.
I added now the missing block to `layout.html` and for me the search is working. In order to test the search locally, you have to allow the browser to reference local files, e.g.
```bash
$ chromium-browser --allow-file-access-from-files
```
Otherwise you will get javascript errors.
For me the output now looks like this:
=> Add missing script block in layout.html

setup.cfg
Sphinx and the RTD theme are slightly broken for newer versions of `docutils`. They have decided to pin `docutils`, see https://github.com/sphinx-doc/sphinx/issues/9088
but this is not integrated into the RTD theme version we are depending on.
As a workaround I will add the pinning to our theme as well.
=> Pin docutils<0.17

sphinx_audeering_theme/static/css/audeering.css
Changes tables in docstrings from
to
=> Fix bottom margin for docstring tables

sphinx_audeering_theme/static/css/audeering.css
Closes #44.
I think it will be easier to read if we indent after the first line in parameter lists, e.g.
=> Indent after first line in parameter lists

sphinx_audeering_theme/footer.html
As discussed recently it makes more sense to point the infrastructure pages link to the actual infrastructure pages and not devops pages. We can link to the devops pages from there, so we only have one entrypoint to the infrastructure.
=> Change link for infrastructure pages

sphinx_audeering_theme/static/css/audeering.css
Closes #46 
This uses bold, black font for every inline code.
=> Use bold + black font for all inline code

sphinx_audeering_theme/static/css/audeering.css
Closes #46 
Use the code default font and black color for function/class names in API definitions.
=> Use black font for class/function name

sphinx_audeering_theme/static/css/audeering.css
We force function arguments in API documentations to be non-italic, e.g.
This had the unwanted side effect, that also italic text in the body of the docstring was forced to be non-italic.
This is fixed by this pull request, e.g.
=> Allow italic font in docstrings

sphinx_audeering_theme/static/css/audeering.css
Closes #57 
This adds two changes to API pages:
* normalize the margin after class property entries
* avoid right floating of class property entries
The examples presented in #57 now look like this:
and
=> Fix margin and floating of class properties

sphinx_audeering_theme/static/css/audeering.css
Follow up on https://github.com/audeering/sphinx-audeering-theme/pull/58.
There was an issue with the margin between `class` and the name of the class in the property field.
=> Fix property definition

sphinx_audeering_theme/footer.html
To increase trust in the links inside the footer, I propose to remove the "Infrastructure" link until there is a page we can link to.
=> Change Infrastructure link to http://devops.pp.audeering.com

.github/workflows/test.yml, sphinx_audeering_theme/__init__.py
Sphinx can speed up building documentation by using multiple processes. In order to do so extensions must indicate that they are safe to be executed in parallel. The original `sphinx_rtd_theme` is safe, so our theme should be safe as well.
=> Mark extension as safe for parallel read/write

sphinx_audeering_theme/footer.html
Changes to footer
* Add `Research` link
* Rename `Documentation` link to `Docs`
* Rename `Infrstructure` link to `Infra`
=> Add Research link to footer

docs/conf.py
Excludes http://devops.pp.audeering.com from the linkcheck.
=> TST: ignore internal link for link check

.github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, setup.cfg, tests/requirements.txt
This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.
=> TST: use pre-commit for flake8 checks

README.rst
To be in line with other packages, this now uses lower case letters and incudes the `-` in the name:
=> DOC: update title to sphinx-audeering-theme

sphinx_audeering_theme/static/css/audeering.css
Add additional styling for the table preview tables introduced in https://github.com/audeering/audbcards/pull/97.
* Adjust font-size of preview table header
* Center font in preview table cell, and reduce height of preview table cell
* Don't use alternating colors for odd and even rows in preview table (was anyway only working for white rows of the tables table)
* Remove vertical lines in table headers
* Remove border on clicked row to make better connection with preview table
The screenshot from https://github.com/audeering/audbcards/pull/97 now looks like
=> Add CSS entries for audbcards preview table
